# Generated by Django 4.2.4 on 2023-09-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Students", new_name="Studentss",),
    ]
