# Generated by Django 4.2.4 on 2023-09-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Customer", new_name="CustomerDetail",),
    ]
