# Generated by Django 4.2.4 on 2023-08-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("created_at", models.DateField(auto_created=True)),
                (
                    "uid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("update_at", models.DateField(auto_now_add=True)),
                ("todo_title", models.CharField(max_length=100)),
                ("todo_description", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
