# Generated by Django 4.2.4 on 2023-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField()),
                ("emp_name", models.CharField(max_length=100)),
                ("emp_location", models.CharField(max_length=100)),
            ],
        ),
    ]
